### ISSUE TITLE
Import template in the "src" attribute 

### ISSUE THREAD

**Issue by jiefmoreno** [vire/jest-vue-preprocessor#23]
**I'm submitting a bug report** 

**Current behavior**

I'm having some trouble with processing vue files that import template in the src attribute: 
Here is the error: 
```sh
Test suite failed to run

TypeError: Cannot read property 'map' of undefined
      
at stringifyStaticRender (node_modules/jest-vue-preprocessor/index.js:83:69)
at Object.process (node_modules/jest-vue-preprocessor/index.js:99:25)
```

**Expected behavior**

Here is my index.vue:
```html
<template src="./template.html"></template>
<script src="./script.js"></script>
<style scoped src="./style.css"></style>
```

* **jest-vue-preprocessor: 1.0.1** 

* **Node version : 8.1.2**

**Comment by jpvincent** [comment]
Also : if the `.vue` file contains the full template, but the JS is still referenced via a `<script>` tag, it also fails.
We had to copy the code of this package and have our own function


```
var fs = require('fs');
const customFreddie = (src, filePath) => {
	var output = src
	//console.log("\n\n\n\n\n\n\n\n\n\n\n" +filePath + "\n\n\n\n\n\n\n")
	// const vueFileName = path.basename(filePath)
	const dirName = path.dirname(filePath)
	var attribute = 'src'
	var regex = new RegExp("<script?\\w+(?:\\s+(?:" + attribute + "=\"([^\"]*)\")|[^\\s>]+|\\s+)*>","gi")
	var matches
	while ( matches = regex.exec(src) )
	{
		if (matches[0] != '<script>') {
			let jsFileName = matches[1]
			let jsCode = fs.readFileSync(path.resolve(dirName, jsFileName), 'utf8')
			//console.log('\n\n\n\n\n\n\n\n\n\n'+jsCode+'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n')
			output += '<script>' + jsCode + '</script>'
		}
	}
	return output
}
```

Sure, we hope to have the time to PR this repository with this code one day

**Comment by vire** [comment]
@jpvincent I'll take a look in upcoming days, I was OoO for a week so need to reconcile first, but as it's an easy fix that shouldn't be an issue.

**Comment by vladferix** [comment]
+1. Having the same issue

**Comment by brenohq** [comment]
+1. Having the same issue

**Comment by djwglpuppy** [comment]
+1 same issue ... script src and template src will not work

**Comment by djwglpuppy** [comment]
I actually Created a fix that works for our org (I forked and referencing it locally for the time being

```js
module.exports = {
  process(src, filePath) {
    // code copied from https://github.com/locoslab/vue-typescript-jest/blob/master/preprocessor.js
    // LICENSE MIT
    // @author https://github.com/locobert
    // heavily based on vueify (Copyright (c) 2014-2016 Evan You)
    const { script, template } = vueCompiler.parseComponent(src, { pad: true });

    if (script.content === '' && script.src !== '') {
      script.content = fs.readFileSync(path.resolve(path.dirname(filePath), script.src), 'utf8');
    }

    if (template.content === '' && template.src !== '') {
      template.content = fs.readFileSync(path.resolve(path.dirname(filePath), template.src), 'utf8');
    }

    const transformedScript = script ? transforms[script.lang || 'babel'](script.content) : '';
    let render;
    let staticRenderFns;
    if (template) {
      const HTML = extractHTML(template, filePath);
      const res = HTML && vueCompiler.compile(HTML);
      render = stringifyRender(res.render);
      staticRenderFns = stringifyStaticRender(res.staticRenderFns);
    }

    return generateOutput(transformedScript, render, staticRenderFns);
  },
};

```

The lines added were:

```js
    if (script.content === '' && script.src !== '') {
      script.content = fs.readFileSync(path.resolve(path.dirname(filePath), script.src), 'utf8');
    }

    if (template.content === '' && template.src !== '') {
      template.content = fs.readFileSync(path.resolve(path.dirname(filePath), template.src), 'utf8');
    }
```

If you think that will work ... lemme know and I can write some tests / exception handle for it and do a pull request

**Comment by grofzero** [comment]
@djwglpuppy Could you copy the whole code here? thx

**Comment by djwglpuppy** [comment]
@grofzero ... the code omitted is the code currently in the index.js file ... so everything between the imports and the exports.   Sorry I can’t do more than that .  Hope that helps

**Comment by grofzero** [comment]
@djwglpuppy I just could'n find the generateOutput function anywhere

**Comment by djwglpuppy** [comment]
@grofzero ... looks like they refactored (though are not supporting src yet? ) . Here is the older file with that function

https://github.com/vire/jest-vue-preprocessor/blob/cd27677520697910be1a15d457e1d2d1fbc0cd02/index.js

**Comment by grofzero** [comment]
@djwglpuppy It still doesn't support src, and thank you very much:)
